INSERT INTO vets VALUES (default, 'James', 'Carter');
INSERT INTO vets VALUES (default, 'Helen', 'Leary');
INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

INSERT INTO specialties VALUES (default, 'radiology');
INSERT INTO specialties VALUES (default, 'surgery');
INSERT INTO specialties VALUES (default, 'dentistry');

INSERT INTO vet_specialties VALUES (2, 1);
INSERT INTO vet_specialties VALUES (3, 2);
INSERT INTO vet_specialties VALUES (3, 3);
INSERT INTO vet_specialties VALUES (4, 2);
INSERT INTO vet_specialties VALUES (5, 1);

INSERT INTO types VALUES (default, 'cat');
INSERT INTO types VALUES (default, 'dog');
INSERT INTO types VALUES (default, 'lizard');
INSERT INTO types VALUES (default, 'snake');
INSERT INTO types VALUES (default, 'bird');
INSERT INTO types VALUES (default, 'hamster');

INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

-- Past visits using explicit column names
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (NULL, '2013-01-01', 'rabies shot', NULL, 'COMPLETED', 0, 'VACCINATION', 7);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (NULL, '2013-01-02', 'rabies shot', NULL, 'COMPLETED', 0, 'VACCINATION', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (NULL, '2013-01-03', 'neutered', NULL, 'COMPLETED', 0, 'SURGERY', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (NULL, '2013-01-04', 'spayed', NULL, 'COMPLETED', 0, 'SURGERY', 7);

-- ==============================================================================
-- MOCK VISITS DATA - 50+ visits for testing chatbot
-- ==============================================================================

-- Past Visits (COMPLETED) - January 2026
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-05 09:00:00', '2026-01-05', 'Annual wellness checkup - all healthy', 'Regular checkup', 'COMPLETED', 0, 'CHECKUP', 1);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-08 10:30:00', '2026-01-08', 'Rabies vaccination booster', 'Annual vaccination', 'COMPLETED', 0, 'VACCINATION', 2);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-10 14:00:00', '2026-01-10', 'Dental cleaning and examination', 'Routine dental care', 'COMPLETED', 0, 'DENTAL', 3);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-12 11:00:00', '2026-01-12', 'Flea and tick treatment', 'Preventive care', 'COMPLETED', 0, 'CHECKUP', 4);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-15 15:30:00', '2026-01-15', 'Skin rash examination', 'Skin irritation concern', 'COMPLETED', 0, 'CHECKUP', 5);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-18 09:30:00', '2026-01-18', 'Blood work and lab tests', 'Annual blood panel', 'COMPLETED', 0, 'CHECKUP', 6);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-20 13:00:00', '2026-01-20', 'Weight management consultation', 'Discuss diet plan', 'COMPLETED', 0, 'CONSULTATION', 7);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-22 10:00:00', '2026-01-22', 'Nail trimming and grooming', 'Regular grooming', 'COMPLETED', 0, 'CHECKUP', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-25 14:30:00', '2026-01-25', 'Wing clipping', 'Routine wing maintenance', 'COMPLETED', 0, 'CHECKUP', 9);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-01-28 11:30:00', '2026-01-28', 'Hip X-rays', 'Hip dysplasia screening', 'COMPLETED', 0, 'CHECKUP', 10);

-- Past Visits (COMPLETED) - February 2026
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-01 09:00:00', '2026-02-01', 'Eye examination', 'Vision check', 'COMPLETED', 0, 'CHECKUP', 11);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-03 10:00:00', '2026-02-03', 'Ear infection treatment', 'Ear drops prescribed', 'COMPLETED', 0, 'CHECKUP', 12);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-05 14:00:00', '2026-02-05', 'Heartworm test', 'Annual screening', 'COMPLETED', 0, 'CHECKUP', 13);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-08 11:00:00', '2026-02-08', 'FVRCP vaccination', 'Feline vaccination', 'COMPLETED', 0, 'VACCINATION', 1);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-10 15:00:00', '2026-02-10', 'Allergy consultation', 'Seasonal allergies', 'COMPLETED', 0, 'CONSULTATION', 2);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-12 09:30:00', '2026-02-12', 'Spay surgery follow-up', 'Post-op checkup', 'COMPLETED', 0, 'FOLLOW_UP', 3);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-15 13:30:00', '2026-02-15', 'Arthritis medication review', 'Adjust pain management', 'COMPLETED', 0, 'CONSULTATION', 4);

-- Current Week Visits (SCHEDULED) - Late February 2026
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-24 10:00:00', '2026-02-24', 'Bordetella vaccination', 'Kennel cough vaccine', 'SCHEDULED', 0, 'VACCINATION', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-24 14:00:00', '2026-02-24', 'Beak trim', 'Overgrown beak', 'SCHEDULED', 0, 'CHECKUP', 9);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-25 09:30:00', '2026-02-25', 'Limping examination', 'Left front leg concern', 'SCHEDULED', 0, 'CHECKUP', 10);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-26 13:00:00', '2026-02-26', 'Urinary tract infection follow-up', 'Recheck after antibiotics', 'SCHEDULED', 0, 'FOLLOW_UP', 11);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-27 08:00:00', '2026-02-27', 'Dental extraction surgery', 'Remove damaged tooth', 'SCHEDULED', 0, 'SURGERY', 12);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-28 11:30:00', '2026-02-28', 'Microchip implantation', 'Permanent ID', 'SCHEDULED', 0, 'CHECKUP', 13);

-- Future Visits - March 2026
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-01 10:00:00', '2026-03-01', 'Hairball treatment', 'Chronic hairball issues', 'SCHEDULED', 0, 'CHECKUP', 1);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-03 14:30:00', '2026-03-03', 'Behavior consultation', 'Excessive chewing', 'SCHEDULED', 0, 'CONSULTATION', 2);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-05 09:00:00', '2026-03-05', 'Ultrasound examination', 'Abdominal scan', 'SCHEDULED', 0, 'CHECKUP', 3);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-07 08:30:00', '2026-03-07', 'Bladder stone removal', 'Surgical procedure', 'SCHEDULED', 0, 'SURGERY', 4);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-10 15:00:00', '2026-03-10', 'Metabolic bone disease checkup', 'Calcium levels', 'PENDING', 0, 'CHECKUP', 5);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-12 11:00:00', '2026-03-12', 'Shed assistance', 'Incomplete shed', 'PENDING', 0, 'CHECKUP', 6);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-14 10:30:00', '2026-03-14', 'Thyroid testing', 'Hormone panel', 'PENDING', 0, 'CHECKUP', 7);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-16 13:30:00', '2026-03-16', 'Lyme disease vaccination', 'Tick prevention', 'PENDING', 0, 'VACCINATION', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-18 09:30:00', '2026-03-18', 'Feather plucking consultation', 'Behavioral issue', 'PENDING', 0, 'CONSULTATION', 9);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-20 08:00:00', '2026-03-20', 'Cruciate ligament surgery', 'ACL repair', 'PENDING', 0, 'SURGERY', 10);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-22 14:00:00', '2026-03-22', 'Cataract examination', 'Vision deterioration', 'PENDING', 0, 'CHECKUP', 11);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-24 10:00:00', '2026-03-24', 'Rabies vaccination', '3-year vaccine', 'PENDING', 0, 'VACCINATION', 12);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-26 08:00:00', '2026-03-26', 'Diabetes glucose curve', 'Blood sugar monitoring', 'PENDING', 0, 'CHECKUP', 13);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-28 11:30:00', '2026-03-28', 'Flea treatment', 'Flea infestation', 'PENDING', 0, 'CHECKUP', 1);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-30 15:00:00', '2026-03-30', 'Heartworm prevention start', 'Begin monthly meds', 'PENDING', 0, 'CHECKUP', 2);

-- Future Visits - April 2026
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-04-02 09:00:00', '2026-04-02', 'Kennel cough treatment', 'Persistent cough', 'PENDING', 0, 'CHECKUP', 3);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-04-05 10:30:00', '2026-04-05', 'Post-surgery staple removal', 'Follow-up care', 'PENDING', 0, 'FOLLOW_UP', 4);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-04-10 09:30:00', '2026-04-10', 'Respiratory infection', 'Wheezing and discharge', 'PENDING', 0, 'EMERGENCY', 6);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-04-15 11:00:00', '2026-04-15', 'Luxating patella examination', 'Knee cap issue', 'PENDING', 0, 'CHECKUP', 8);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-04-20 08:30:00', '2026-04-20', 'Geriatric blood panel', 'Senior wellness', 'PENDING', 0, 'CHECKUP', 10);

-- Cancelled Visits
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-08 10:00:00', '2026-03-08', 'Routine checkup', 'Owner cancelled - rescheduled', 'CANCELLED', 0, 'CHECKUP', 1);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-03-13 14:00:00', '2026-03-13', 'Dental cleaning', 'Pet not fasting', 'CANCELLED', 0, 'DENTAL', 5);

-- Emergency visits today
INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-24 16:45:00', '2026-02-24', 'Foreign object ingestion', 'URGENT - ate toy', 'SCHEDULED', 0, 'EMERGENCY', 6);

INSERT INTO visits (APPOINTMENT_TIME, VISIT_DATE, DESCRIPTION, REQUEST_NOTES, STATUS, VERSION, VISIT_TYPE, PET_ID)
VALUES (TIMESTAMP '2026-02-24 17:30:00', '2026-02-24', 'Difficulty breathing', 'URGENT - respiratory distress', 'SCHEDULED', 0, 'EMERGENCY', 11);
